#!/usr/bin/env sh
# depends: coreutils(gnu)
set -eu
IFS=$(printf ' \n\t')


usage(){
    cmd=$(echo "$(basename "$0")"%.*)
    cat << HELP
Usage:
${cmd} [options] [args...]

SAY HELLO

HELP
}

usage

